routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/', function () {
    return view('home');
});


Auth::routes();


Route::group(['middleware' => 'auth'], function(){
	

Route::resource('department','DepartmentController');
Route::resource('class','ClassesController');
Route::resource('student','StudentController');
Route::resource('dashboard','DashboardController');


});

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected $fillable = ['name'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Department;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $department = Department::all();
        return view('backend.department.index',compact('department'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,
            ['name' => 'required'


        ]);

        Department::create($request->all());
        return redirect()->route('department.index')->with('status','Department Added Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $department = Department::find($id);
        return view('backend.department.edit',compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $this->validate($request,
            ['name' => 'required'

        ]);

        Department::find($id)->update($request->all());
        return redirect()->route('department.index')->with('status','updated successfully');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Department::find($id)->delete();
        return redirect()->route('department.index')->with('status','deleted successfully');
    }
}

resources/views/backend/department/user/index.blade.php
@extends('layouts.master')
@section('content')
<!-- /.row -->
<section class="content">
		<p class="pull-right">
			<a href="{{route('department.create')}}" class="btn btn-sm btn-success">Add Department</a>
	  	</p>
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
            <div class="box-header">
              <h3 class="box-title">Departments</h3>
              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
           
              <table class="table table-hover table-bordered">
                <tr>
                  <th>Department Id</th>
                  <th>Department</th>
                 
                  <th>Action</th>
                </tr>
              
               @foreach($department as $department)
                <tr>
                  <td>{{$department->id}}</td>
                  <td>{{$department->name}}</td>
                  
                  
                  <td>
                  	<label class="switch">
          					  <input type="checkbox" class="update-status"  data-id="" data-url="" >
          					  <span class="slider round"></span>
          					</label>
                  </td>
                    
                  <td> 
                    <form action="{{route('department.destroy',$department->id)}}" method="post" role="form">
                      @csrf

                  			<!-- <a href=""><button type="button" title="view" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button></a> -->

                            <a href="{{route('department.edit',$department->id)}}"><button type="button" title="edit" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit"></span></button></a>
                              <input type="hidden" name="_method" value="DELETE"> 
                            <button  title="Delete" type="submit" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete this user?');"><span class="glyphicon glyphicon-trash"></span></button>
                  </td></form>
                </tr>
               
               @endforeach
              </table>
             
	            <div><h2></h2></div>
	          
            </div>

            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
      </section>
      @endsection