routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/', function () {
    return view('home');
});


Auth::routes();


Route::group(['middleware' => 'auth'], function(){
	

Route::resource('department','DepartmentController');
Route::resource('class','ClassesController');
Route::resource('student','StudentController');
Route::resource('dashboard','DashboardController');


});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = ['name', 'class','mobile','permanent_address', 'present_address',
     'reg_id' , 'dep_id' ,'roll' , 'father_name',

    ];
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $student = Student::all();
        return view('backend.student.index',compact('student'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.student.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Student::create($request->all());
        return redirect()->route('student.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Student::find($id);
        return view('backend.student.edit',compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Student::find($id)->update($request->all());
        return redirect()->route('student.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Student::find($id)->delete();
         return redirect()->route('student.index');

    }
}

resources/views/backend/student/create.blade.php
@extends('layouts.master')
@section('content')


<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add Class</h3>
               @if (session('status'))
				<p style="color: green;">{{session('status')}}</p>
			@endif
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{route('student.store')}}" method="post" enctype="multipart/form-data">
            	@csrf
              <div class="box-body">
              	<div class="row">
	              	<div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Student Name</label>
		                  <input type="text" name="name" class="form-control" placeholder="Enter student name">
		                  
		                  <div class="text-danger">{{ $errors->first('name') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Class</label>
		                  <input type="text" name="class" class="form-control" placeholder="Enter Class">
		                  
		                  <div class="text-danger">{{ $errors->first('class') }}</div>
		                </div>
	                </div>


	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Roll Number</label>
		                  <input type="text" name="roll" class="form-control" placeholder="Enter Roll">
		                  
		                  <div class="text-danger">{{ $errors->first('roll') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Father Name</label>
		                  <input type="text" name="father_name" class="form-control" placeholder="Father Name">
		                  
		                  <div class="text-danger">{{ $errors->first('father_name') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Registration ID</label>
		                  <input type="text" name="reg_id" class="form-control" placeholder="Registration ID">
		                  
		                  <div class="text-danger">{{ $errors->first('reg_id') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Department ID</label>
		                  <input type="text" name="dep_id" class="form-control" placeholder="Department ID">
		                  
		                  <div class="text-danger">{{ $errors->first('dep_id') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Permanent Address</label>
		                  <input type="text" name="permanent_address" class="form-control" placeholder="permanent Address">
		                  
		                  <div class="text-danger">{{ $errors->first('permanent_address') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Present Address</label>
		                  <input type="text" name="present_address" class="form-control" placeholder="Current Address">
		                  
		                  <div class="text-danger">{{ $errors->first('present_address') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Mobile</label>
		                  <input type="text" name="mobile" class="form-control" placeholder="Mobile">
		                  
		                  <div class="text-danger">{{ $errors->first('mobile') }}</div>
		                </div>
	                </div>
	                
	                


              </div>
              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href=""><button type="button" class="btn btn-danger">Cancel</button>
              </div>
          </form>
		</div>
	</div>
</section>
@endsection

resources/views/backend/student/edit.blade.php
@extends('layouts.master')
@section('content')


<section class="content">
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add Class</h3>
               @if (session('status'))
				<p style="color: green;">{{session('status')}}</p>
			@endif
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="{{route('student.update',$student->id)}}" method="post" enctype="multipart/form-data">
            	<input type="hidden" name="_method" value="PUT">
            	@csrf
              <div class="box-body">
              	<div class="row">
	              	<div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Student Name</label>
		                  <input type="text" name="name" class="form-control" value="{{$student->name}}">
		                  
		                  <div class="text-danger">{{ $errors->first('name') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Class</label>
		                  <input type="text" name="class" class="form-control" value="{{$student->class}}">
		                  
		                  <div class="text-danger">{{ $errors->first('class') }}</div>
		                </div>
	                </div>


	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Roll Number</label>
		                  <input type="text" name="roll" class="form-control" value="{{$student->roll}}">
		                  
		                  <div class="text-danger">{{ $errors->first('roll') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Father Name</label>
		                  <input type="text" name="father_name" class="form-control" value="{{$student->father_name}}">
		                  
		                  <div class="text-danger">{{ $errors->first('father_name') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Registration ID</label>
		                  <input type="text" name="reg_id" class="form-control" value="{{$student->reg_id}}">
		                  
		                  <div class="text-danger">{{ $errors->first('reg_id') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Department ID</label>
		                  <input type="text" name="dep_id" class="form-control" value="{{$student->dep_id}}">
		                  
		                  <div class="text-danger">{{ $errors->first('dep_id') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Permanent Address</label>
		                  <input type="text" name="permanent_address" class="form-control" value="{{$student->permanent_address}}">
		                  
		                  <div class="text-danger">{{ $errors->first('permanent_address') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Present Address</label>
		                  <input type="text" name="present_address" class="form-control" value="{{$student->present_address}}">
		                  
		                  <div class="text-danger">{{ $errors->first('present_address') }}</div>
		                </div>
	                </div>

	                <div class="col-md-6">
		                <div class="form-group">
		                  <label for="exampleInputEmail1">Mobile</label>
		                  <input type="text" name="mobile" class="form-control" value="{{$student->mobile}}">
		                  
		                  <div class="text-danger">{{ $errors->first('mobile') }}</div>
		                </div>
	                </div>
	                
	                


              </div>
              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href=""><button type="button" class="btn btn-danger">Cancel</button>
              </div>
          </form>
		</div>
	</div>
</section>
@endsection

resources/views/backend/student/index.blade.php
@extends('layouts.master')
@section('content')
<!-- /.row -->
<section class="content">
		<p class="pull-right">
			<a href="{{route('student.create')}}" class="btn btn-sm btn-success">Add student Information</a>
	  	</p>
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
            <div class="box-header">
              <h3 class="box-title">Students</h3>
              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
           
              <table class="table table-hover table-bordered">
                <tr>
                  <th>Student Id</th>
                  <th>Name</th>
                  <th>Class</th>
                  <th>Roll Number</th>
                  <th>Father Name</th>
                  <th>Registration Id</th>
                 
                  <th>Department Id</th>
                  <th>Permanent Address</th>
                  <th>Present Address</th>
                   <th>Mobile Number</th>
                  
                </tr>
             @foreach($student as $student)
               
                <tr>
                  <td>{{$student->id}}</td>
                  <td>{{$student->name}}</td>
                  <td>{{$student->class}}</td>
                  <td>{{$student->roll}}</td>
                  <td>{{$student->father_name}}</td>
                  <td>{{$student->reg_id}}</td>
                  <td>{{$student->dep_id}}</td>
                  <td>{{$student->permanent_address}}</td>
                  <td>{{$student->present_address}}</td>
                  <td>{{$student->mobile}}</td>
                  
                  
                  <td>
                  	<label class="switch">
          					  <input type="checkbox" class="update-status"  data-id="" data-url="" >
          					  <span class="slider round"></span>
          					</label>
                  </td>
                    
                  <td> 
                    <form action="" method="post" role="form">
                      @csrf

                  			<!-- <a href=""><button type="button" title="view" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-eye-open"></span></button></a> -->

                            <a href="{{route('student.edit',$student->id)}}"><button type="button" title="edit" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-edit"></span></button></a>
                              <input type="hidden" name="_method" value="DELETE"> 
                            <button  title="Delete" type="submit" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete this user?');"><span class="glyphicon glyphicon-trash"></span></button>
                  </td></form>
                </tr>
              
              @endforeach
              </table>
             
	            <div><h2></h2></div>
	          
            </div>

            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
      </section>
      @endsection